version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000
  test:
    build: .
    command: pytest
  lint:
    build: .
    command: flake8 app.py